version: '3.1'

services:

  mongo:
    image: rafibz007/restaurant-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/rafibz007/mongo_data:/data/db

  backend:
    image: rafibz007/restaurant-backend
    restart: always
    environment:
      DB_CONNECTION: mongodb://root:password@mongo:27017/?retryWrites=true&w=majority
      JWT_SECRET: 09f26e402586e2faa8da4c98a35f1b20d6b033c6097befa8be3486a829587fe2f90a832bd3ff9d42710a4da095a2ce285b009f0c3730cd9b8e1af3eb84df6611
    ports:
      - 3000:3000

  frontend:
    image: rafibz007/restaurant-frontend
    restart: always
    ports:
      - 4200:80

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/